import type { Publication } from "@/lib/content";

export const publicationCache: Publication[] = [
  {
    id: "ff07908e-fc46-4077-a204-46a29d6d78e3",
    kind: "journal",
    title: "Hydromagnetic casson nanofluid flow past a wedge in a porous medium in the presence of induced magnetic field",
    authors: "N. Danson, J. Ochwach, K. Jacob, and M. Okongo",
    venue: "American Journal of Applied Mathematics, vol. 13, no. 1, pp. 30-56",
    year: 2025,
    doi: "https://doi.org/10.11648/j.ajam.20251301.13",
    article_url: "https://doi.org/10.11648/j.ajam.20251301.13",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 1,
  },
  {
    id: "aa5c0548-b804-45b3-8edd-b345488ba667",
    kind: "journal",
    title: "A mathematical model for effective fungicide use in rice blast re-infection",
    authors: "J. Ochwach, O. B., and O. M. O.",
    venue: "Journal of Mathematical Analysis and Modeling, vol. 6, no. 1, pp. 117-143",
    year: 2025,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 2,
  },
  {
    id: "64f678e6-21ee-4060-8ce7-43267671c742",
    kind: "journal",
    title: "Mathematical modelling with optimal control of infectious diseases with vaccination",
    authors: "H. M. Wanjala, M. O. Okongo, and J. O. Ochwach",
    venue: "Computational Methods for Differential Equations",
    year: 2025,
    doi: "https://doi.org/10.22034/cmde.2024.62350.2743",
    article_url: "https://doi.org/10.22034/cmde.2024.62350.2743",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 3,
  },
  {
    id: "9f4c7775-d6d7-40f4-b468-154b2ce04918",
    kind: "journal",
    title: "Mathematical model of an infectious respiratory disease with a double-dose vaccine, isolation and use of face-mask",
    authors: "H. M. Wanjala, M. O. Okongo, and J. Ochwach",
    venue: "International Journal of Mathematical Sciences and Computing, vol. 11, no. 2, pp. 10-27",
    year: 2025,
    doi: "https://doi.org/10.5815/ijmsc.2025.02.02",
    article_url: "https://doi.org/10.5815/ijmsc.2025.02.02",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 4,
  },
  {
    id: "2e6d8037-52c6-4dff-ac7b-e74d31167e93",
    kind: "journal",
    title: "Mathematical model of alcoholism incorporating treatment: A case study in Kenya",
    authors: "S. Chege, M. O. Okongo, and J. O. Ochwach",
    venue: "Journal of Mathematics Instruction, Social Research and Opinion, vol. 4, no. 1, pp. 73-90",
    year: 2024,
    doi: "https://doi.org/10.58421/misro.v4i1.316",
    article_url: "https://doi.org/10.58421/misro.v4i1.316",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 5,
  },
  {
    id: "c21f942f-8655-400e-ae4e-b6f44df23689",
    kind: "journal",
    title: "Modelling fluid flow in zone 2 of an open horseshoe channel with lateral inflow channels",
    authors: "J. Jason, M. Okongo, J. Kirimi, and J. Ochwach",
    venue: "Journal of Advances in Mathematics and Computer Science, vol. 39, no. 8, pp. 33-42",
    year: 2024,
    doi: "https://doi.org/10.9734/jamcs/2024/v39i81919",
    article_url: "https://doi.org/10.9734/jamcs/2024/v39i81919",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 6,
  },
  {
    id: "d8af3d52-574c-4b18-baea-2f93f33a8533",
    kind: "journal",
    title: "Modelling fluid flow of an open horseshoe channel with lateral inflow channels",
    authors: "J. Jason, M. Okongo, J. Kirimi, and J. Ochwach",
    venue: "Journal of Advances in Mathematics and Computer Science, vol. 39, no. 7, pp. 34-44",
    year: 2024,
    doi: "https://doi.org/10.9734/jamcs/2024/v39i71910",
    article_url: "https://doi.org/10.9734/jamcs/2024/v39i71910",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 7,
  },
  {
    id: "1624af5c-f27e-47bc-af2a-cb055335abf1",
    kind: "journal",
    title: "Modeling the impact of flow parameters on fluid velocity and temperature in an electrically conducting fluid past a wedge",
    authors: "D. Nyaga, J. Kirimi, J. Ochwach, and M. Okongo",
    venue: "International Journal of Multidisciplinary Sciences and Engineering, vol. 15, no. 4",
    year: 2024,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 8,
  },
  {
    id: "1a0377e1-ee4e-4200-8173-ad94fa7d6491",
    kind: "journal",
    title: "Mathematical modelling for rice blast re-infection",
    authors: "B. O. Obita, M. O. Okongo, J. O. Ochwach, and A. M. Lunani",
    venue: "American Journal of Applied Mathematics, vol. 12, no. 2, pp. 37-49",
    year: 2024,
    doi: "https://doi.org/10.11648/j.ajam.20241202.12",
    article_url: "https://doi.org/10.11648/j.ajam.20241202.12",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 9,
  },
  {
    id: "9c9e1789-0d9f-46ee-b65a-cc5436a39ff1",
    kind: "journal",
    title: "Bifurcation analysis of an infectious respiratory disease with lockdown and social distancing",
    authors: "H. Wanjala, M. Okongo, and J. Ochwach",
    venue: "ARRUS Journal of Mathematics and Applied Science, vol. 4, no. 2, pp. 118-134",
    year: 2024,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 10,
  },
  {
    id: "54b95020-2a1b-4c1d-91b5-4fa8fd2c2ca9",
    kind: "journal",
    title: "Mathematical model of the impact of home-based care on contagious respiratory illness under optimal conditions",
    authors: "H. M. Wanjala, M. O. Okongo, and J. O. Ochwach",
    venue: "Jambura Journal of Biomathematics, vol. 5, no. 2, pp. 83-94",
    year: 2024,
    doi: "https://doi.org/10.37905/jjbm.v5i2.27611",
    article_url: "https://doi.org/10.37905/jjbm.v5i2.27611",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 11,
  },
  {
    id: "974dd1b4-d42c-4b32-9f99-f818eca6c62e",
    kind: "journal",
    title: "Stability analysis of a sterile insect technique model for controlling false codling moth",
    authors: "J. Ochwach, M. Okongo, and M. Muraya",
    venue: "Journal of Mathematical Analysis and Modeling, vol. 4, no. 1, pp. 78-105",
    year: 2023,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 12,
  },
  {
    id: "434874f7-3aea-4080-9bff-a97fd82512dc",
    kind: "journal",
    title: "On basic reproduction number R0: Derivation and application",
    authors: "J. O. Ochwach, M. O. Okongo, and A. L. M. Murwayi",
    venue: "Journal of Engineering and Applied Sciences Technology, SRC/JEAST-234",
    year: 2023,
    doi: "https://doi.org/10.47363/JEAST/2023(5)173",
    article_url: "https://doi.org/10.47363/JEAST/2023(5)173",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 13,
  },
  {
    id: "31c4dc17-6533-4a41-a6ba-5ef0510eab6c",
    kind: "journal",
    title: "The impact of HIV/AIDS treatment and counseling on the prevalence of tuberculosis and malaria co-infections",
    authors: "M. O. Okongo, M. A. Lunani, B. K. Menge, and J. O. Ochwach",
    venue: "International Journal of Mathematical Analysis, vol. 17, no. 2, pp. 51-67",
    year: 2023,
    doi: "https://doi.org/10.12988/ijma.2023.511270",
    article_url: "https://doi.org/10.12988/ijma.2023.511270",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 14,
  },
  {
    id: "f096237f-a601-4825-b643-54fcf67f1400",
    kind: "journal",
    title: "Impact of media awareness and use of face-masks on infectious respiratory disease",
    authors: "H. M. Wanjala, M. O. Okongo, and J. O. Ochwach",
    venue: "Pan-American Journal of Mathematics, vol. 2, p. 15",
    year: 2023,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 15,
  },
  {
    id: "1266f260-40e7-49b0-862a-9573c3df602f",
    kind: "journal",
    title: "Mathematical modelling of cholera incorporating the dynamics of the induced achlorhydria condition and treatment",
    authors: "C. Ngari, C. G. Ngari, M. Okongo, and J. Ochwach",
    venue: "Journal of Progressive Research in Mathematics, vol. 19, no. 2, pp. 60-88",
    year: 2022,
    doi: "http://scitecresearch.com/journals/index.php/jprm/article/view/2168",
    article_url: "http://scitecresearch.com/journals/index.php/jprm/article/view/2168",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 16,
  },
  {
    id: "16af4964-a1a6-42c3-a22b-7c4a15b5bc82",
    kind: "journal",
    title: "Mathematical modelling and simulation of nitrate leaching into groundwater",
    authors: "J. Ochwach, M. Okongo, and O. Ochieng",
    venue: "International Journal of Systems Science and Applied Mathematics, vol. 7, no. 4, pp. 74-84",
    year: 2022,
    doi: "https://doi.org/10.11648/j.ijssam.20220704.12",
    article_url: "https://doi.org/10.11648/j.ijssam.20220704.12",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 17,
  },
  {
    id: "0dffa21e-023d-4360-85b9-3df06c21eb43",
    kind: "journal",
    title: "Mathematical model for false codling moth control using pheromone traps",
    authors: "J. Ochwach, M. O. Okongo, and M. M. Muraya",
    venue: "International Journal of Applied Mathematical Research, vol. 10, no. 2, pp. 32-52",
    year: 2021,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 18,
  },
  {
    id: "6ecbf6a1-723f-4302-bfe6-2cc3ebec2f4a",
    kind: "journal",
    title: "Mathematical modelling of host-pest interactions in stage-structured populations: A case of false codling moth (Thaumatotibia leucotreta)",
    authors: "J. O. Ochwach, M. O. Okongo, and M. M. Muraya",
    venue: "Journal of Progressive Research in Mathematics, vol. 18, no. 4, pp. 1-21",
    year: 2021,
    doi: "http://scitecresearch.com/journals/index.php/jprm/article/view/2087",
    article_url: "http://scitecresearch.com/journals/index.php/jprm/article/view/2087",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 19,
  },
  {
    id: "fcd30505-01a2-4b47-8c12-40329e8832d4",
    kind: "journal",
    title: "Stability analysis of the modified advection-dispersion model for the leaching of nitrates into groundwater",
    authors: "O. J. Ochwach, S. W. Musundi, and M. O. Okongo",
    venue: "Journal of Progressive Research in Mathematics, vol. 14, no. 2",
    year: 2018,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 20,
  },
  {
    id: "70547230-7e25-4cb6-8e14-070560c44a09",
    kind: "journal",
    title: "Modelling the impact of soil porosity on nitrate leaching to groundwater using the advection dispersion equation",
    authors: "O. J. Ochwach, M. O. Okongo, and S. W. Musundi",
    venue: "IOSR Journal of Mathematics, vol. 14, no. 4, pp. 18-26",
    year: 2018,
    doi: "http://www.iosrjournals.org",
    article_url: "http://www.iosrjournals.org",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 21,
  },
  {
    id: "f04bbb33-8aa4-4df1-9b13-11afd18dd7eb",
    kind: "conference",
    title: "Mathematical modeling on the impact of lockdown and social distancing on an infectious respiratory disease",
    authors: "H. M. Wanjala, M. O. Okongo, and J. Ochwach",
    venue: "15th KEMRI Annual Scientific and Health Conference",
    year: 2025,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 1,
  },
  {
    id: "7cfad709-fb7e-4f2f-9274-f0bc42ed02bc",
    kind: "conference",
    title: "Mathematical model of alcoholism incorporating treatment: A case study in Kenya",
    authors: "S. C. Kimani, J. O. Ochwach, and M. O. Okongo",
    venue: "11th Chuka University Annual International Conference",
    year: 2024,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 2,
  },
  {
    id: "d7b7d1d4-f10e-4608-bcdb-d6388c45c04b",
    kind: "conference",
    title: "Mathematical model of COVID-19 with a double-dose vaccine",
    authors: "H. M. Wanjala, M. O. Okongo, and J. Ochwach",
    venue: "14th KEMRI Annual Scientific & Health Conference, Safari Park Hotel and Casino",
    year: 2023,
    doi: "https://www.kemri.go.ke/wp-content/uploads/2024/02/14-KASH-ABSTRACT-BOOK-1.pdf",
    article_url: "https://www.kemri.go.ke/wp-content/uploads/2024/02/14-KASH-ABSTRACT-BOOK-1.pdf",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 3,
  },
  {
    id: "783aed3f-83e2-4a46-adc5-e8df35b6a1b5",
    kind: "conference",
    title: "The impact of home-based care on infectious respiratory disease: A case of COVID-19",
    authors: "H. M. Wanjala, M. O. Okongo, and J. Ochwach",
    venue: "14th KEMRI Annual Scientific & Health Conference, Safari Park Hotel and Casino",
    year: 2023,
    doi: "https://www.kemri.go.ke/wp-content/uploads/2024/02/14-KASH-ABSTRACT-BOOK-1.pdf",
    article_url: "https://www.kemri.go.ke/wp-content/uploads/2024/02/14-KASH-ABSTRACT-BOOK-1.pdf",
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 4,
  },
  {
    id: "5e17c6aa-d633-4df5-bea7-43bba45ec693",
    kind: "conference",
    title: "COVID-19 transmission dynamics model with double-dose vaccination and use of face masks: A case study in Kenya",
    authors: "H. M. Wanjala, M. O. Okongo, and J. O. Ochwach",
    venue: "10th Chuka University Annual International Conference",
    year: 2023,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 5,
  },
  {
    id: "8106d08f-9d54-4f1d-89fc-87b30522e42d",
    kind: "conference",
    title: "Mathematical modelling of the sterile insect technique for control of false codling moth",
    authors: "J. Ochwach",
    venue: "8th Chuka University Annual International Conference",
    year: 2021,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 6,
  },
  {
    id: "de14a862-9f67-4c93-bbb6-dc3003c67919",
    kind: "conference",
    title: "A note on the basic reproduction number: Novel coronavirus (2019-nCoV)",
    authors: "J. Ochwach",
    venue: "Conference presentation",
    year: 2020,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 7,
  },
  {
    id: "ee18426d-1b6d-4d22-804c-3cd9a733564f",
    kind: "conference",
    title: "Effect of harvesting and stocking under delayed time regulation on the logistic population model",
    authors: "J. Ochwach",
    venue: "Conference presentation",
    year: 2019,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 8,
  },
  {
    id: "81b7d0da-a4a7-434d-a524-839beb85b1fa",
    kind: "conference",
    title: "Modelling nitrate leaching to groundwater using a modified diffusion advection equation",
    authors: "J. Ochwach",
    venue: "5th Chuka University Annual International Research Conference",
    year: 2018,
    doi: null,
    article_url: null,
    pdf_url: null,
    pdf_download_allowed: true,
    sort_order: 9,
  },
];
