/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupervisionRouteImport } from './routes/supervision'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIdRouteImport } from './routes/resources.$id'
import { Route as PublicationsIdRouteImport } from './routes/publications.$id'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const SupervisionRoute = SupervisionRouteImport.update({
  id: '/supervision',
  path: '/supervision',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResourcesRoute,
} as any)
const PublicationsIdRoute = PublicationsIdRouteImport.update({
  id: '/publications/$id',
  path: '/publications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/student': typeof StudentRoute
  '/supervision': typeof SupervisionRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/student': typeof StudentRoute
  '/supervision': typeof SupervisionRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/student': typeof StudentRoute
  '/supervision': typeof SupervisionRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/publications/$id': typeof PublicationsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blogs'
    | '/contact'
    | '/research'
    | '/reset-password'
    | '/resources'
    | '/student'
    | '/supervision'
    | '/blogs/$slug'
    | '/publications/$id'
    | '/resources/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blogs'
    | '/contact'
    | '/research'
    | '/reset-password'
    | '/resources'
    | '/student'
    | '/supervision'
    | '/blogs/$slug'
    | '/publications/$id'
    | '/resources/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blogs'
    | '/contact'
    | '/research'
    | '/reset-password'
    | '/resources'
    | '/student'
    | '/supervision'
    | '/blogs/$slug'
    | '/publications/$id'
    | '/resources/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ContactRoute: typeof ContactRoute
  ResearchRoute: typeof ResearchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  StudentRoute: typeof StudentRoute
  SupervisionRoute: typeof SupervisionRoute
  PublicationsIdRoute: typeof PublicationsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supervision': {
      id: '/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof SupervisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/publications/$id': {
      id: '/publications/$id'
      path: '/publications/$id'
      fullPath: '/publications/$id'
      preLoaderRoute: typeof PublicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface ResourcesRouteChildren {
  ResourcesIdRoute: typeof ResourcesIdRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesIdRoute: ResourcesIdRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ContactRoute: ContactRoute,
  ResearchRoute: ResearchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  StudentRoute: StudentRoute,
  SupervisionRoute: SupervisionRoute,
  PublicationsIdRoute: PublicationsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
